### ISSUE TITLE
Request - API Changes for 2.3.0

### ISSUE THREAD

**Issue by AnthonyMDev** [mRs-/HexColors#22]
Since the API changed with the new version, according to semantic versioning, shouldn't the version number be bumped to 3.0.0? By not changing the major version, people who were depending on the old cocoa pod have had the pod automatically updated to the next minor version (2.3.0) and their projects are breaking. (This includes me).

Since the update to the APIs have broken my project, can we get at change log that explains the API changes for 2.3.0 and what I need to be looking at to migrate to the new version?

Thanks

**Comment by mRs-** [comment]
The main problem is, that this library is heavily used by TSMessages and we got a bug in the dependencies of TSMessages.

IMHO it was not a big issue to me at first but it's developing to a big one for many other people. Yeah it broke my build server as well because of some mistakes in other dependencies.

I bumped it not to 3.0.0 because none of the API has changed at all, only the import path has changed for the carthage support.

Change log is now up on https://github.com/mRs-/HexColors/releases/tag/2.3.0

**Comment by AnthonyMDev** [comment]
Thank you for the Change Log.
Now I see that it's a minor change to make, but it still meant I had to spend over an hour fixing dependencies in multiple legacy projects of mine. It's not a huge deal, but I'm sure I wasn't the only one to have the issue, so I wanted to bring it to your attention.

My personal opinion is that any change that has the potential to break legacy code dependent upon the library should result in a major version bump. It's not like there is a limit to the number of major versions you can release.

Thanks again for the awesome, very useful library!
