### ISSUE TITLE
API is not correctly translated to Swift in Xcode 7.3

### ISSUE THREAD

**Issue by lumaxis** [mRs-/HexColors#35]
With the switch to Swift 2.2, HexColors' Obj-C API is not correctly translated to Swift anymore:

<img width="610" alt="screenshot 2016-01-29 03 16 34" src="https://cloud.githubusercontent.com/assets/406937/12665266/d6e2fe5e-c636-11e5-9e23-1793cb2feeb3.png">

<img width="1051" alt="screenshot 2016-01-29 03 17 15" src="https://cloud.githubusercontent.com/assets/406937/12665271/db6ec5e8-c636-11e5-8520-4e247315d274.png">

**Comment by mRs-** [comment]
I think this is not exactly a problem of HexColors instead it's the Swift API Transformation mentioned in here (https://swift.org/blog/swift-api-transformation/). 

Swift 2.2 is dropping the `with8Bit` or some think we know already from UIImage `UIImage(name:)` instead of `UIImage(imageWithName:)`.

Did you tried it without the with8Bit prefix?

**Comment by lumaxis** [comment]
@mRs- Yep, I tried but the annoying thing is that the Swift compiler insists on removing `red:` too so only something like this works: `UIColor(246, green: 247, blue: 250)`

**Comment by mRs-** [comment]
Okay, that's not the expected way, there is some work needed. I try to fix this as soon as possible, but maybe you got this already and can hand in a pull request?

**Comment by mRs-** [comment]
will be closed with https://github.com/mRs-/HexColors/tree/swift-3.0
